GET http://localhost:8083/allocate?
    megabytes=10000&
    type=short
Accept: application/json

###
GET http://localhost:8083/allocate?
    megabytes=10000&
    type=long
Accept: application/json

###
GET http://localhost:8083/clear
Accept: application/json
