management.prometheus.metrics.export.enabled=true
management.endpoints.web.exposure.include=health,info,metrics,prometheus
logging.level.root=DEBUG
logging.level.sun.rmi=info
logging.level.javax.management.remote.rmi=info

spring.config.import=application-google.properties
