spring:
  application:
    name: service2
  config:
    import: classpath:services.yml, classpath:datadog.yml, classpath:logging.yml, classpath:tracing.yml
  main:
    allow-bean-definition-overriding: true
server:
  port: 8082

management:
  metrics:
    export:
      statsd:
        enabled: false